# Generated by Django 5.1.4 on 2025-01-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
